### ISSUE TITLE
Actualización de horarios de los módulos

### ISSUE THREAD

**Issue by Javo2804** [aurmeneta/HorarioUC#28]
Hola! Dejo esta issue para mencionar el [cambio de los horarios de los módulos de clases a partir de este semestre](https://registrosacademicos.uc.cl/wp-content/uploads/2023/05/Estructura-de-modulacion-horaria-desde-2023-22.pdf).

En principio, una solución rápida para este problema podría ser simplemente modificar los horarios de cada módulo e insertar la fila del almuerzo después del módulo 4 en lugar de antes. O sea,invertir las líneas 72 y 73 en el siguiente código: https://github.com/aurmeneta/HorarioUC/blob/d8a8d033be39757850f6a6da09860c8a2c8a29c3/src/components/Tables/Horario.jsx#L69-L75

Ahora, lo que mencioné es sin considerar alguna compatibilidad con semestres anteriores.

Gracias, HorarioUC me da vida :)

**Comment by aurmeneta** [comment]
Implementado en #29
