### ISSUE TITLE
No se muestra el campo Nivel, que a veces reemplaza a Escuela en las vacantes

### ISSUE THREAD

**Issue by eanorambuena** [aurmeneta/HorarioUC#32]
# No se muestra el campo Nivel, que a veces se usa en desmedro de Escuela en la sección de vacantes
### Horario UC
![image](https://github.com/aurmeneta/HorarioUC/assets/38821970/51cc1b5b-8b8a-4ded-824a-dda82286351a)
### Buscacursos
![image](https://github.com/aurmeneta/HorarioUC/assets/38821970/7b4ee4e8-4281-43b1-9871-c22cf248d1b5)

**Comment by aurmeneta** [comment]
Hola @eanorambuena, muchas gracias por tu comentario. Efectivamente la información sobre cupos está incompleta. Para solucionarlo acá, primero hay que agregar esas columnas en la librería que ocupo para hacer scraping (ver aurmeneta/BuscaCursosUC#12). 

Una vez haya hecho eso, implemento la solución acá.

Saludos
