### ISSUE TITLE
Detalle cupos

### ISSUE THREAD

**Issue by pepinofdz** [aurmeneta/HorarioUC#8]
Más que problemas del proyecto, son oportunidades de mejora:

Se podría agregar el detalle de los cupos que quedan, para facilitar el uso de la plataforma (ej: cupos exclusivos para ingeniería, quedan cupos pero son exclusivos para college). O similarmente, se podría poner un box que pregunte la carrera, para que se use ese filtro al dar las opciones de horario.

Además, se podría dejar una parte para recibir feedback general para ir mejorando el proyecto.

**Comment by aurmeneta** [comment]
Muchas gracias por tus comentarios. Te cuento que estamos terminando de implementar HorarioUC en [RamosUC](https://github.com/open-source-uc/ramos-uc). La implementación considera dar más detalles de los cupos.

Respecto a tus otros comentarios, los tendremos en cuenta en las próximas modificaciones que hagamos.

Te invito a que pases por [RamosUC](https://github.com/open-source-uc/ramos-uc) y si quieres también puedes abrir un Issue para darnos feedback!
